title: Yuc's Homepage
page-top-title: Yuc
top-section-bg-text: Be what you wanna be
home-subtitle: Yuc;Electronic and Information Engineering;
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
